spring:
  config:
    import: "kubernetes:"
  application:
    name: service-demo
  cloud:
    kubernetes:
      reload:
        enabled: true
      config:
        namespace: config-playground
        sources:
          - labels:
              config: k8s-sourced-data

management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: restart,health

logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG
