apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbdemo
  labels:
    app: sbdemo
spec:
  selector:
    matchLabels:
      app: sbdemo
  template:
    metadata:
      labels:
        app: sbdemo
    spec:
      containers:
        - name: sbdemo
          image: config-files/main
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: projected
              mountPath: /config
      volumes:
        - name: projected
          projected:
            sources:
              - configMap:
                  name: demo-configmap
              - configMap:
                   name: second-configmap
