apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: config-playground
  name: service-demo
  labels:
    app: service-demo
spec:
  selector:
    matchLabels:
      app: service-demo
  template:
    metadata:
      labels:
        app: service-demo
    spec:
      containers:
        - name: service-demo
          image: config-files/main
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: projected
              mountPath: /config
      volumes:
        - name: projected
          projected:
            sources:
              - configMap:
                  name: demo-configmap
              - configMap:
                  name: second-configmap
