apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-demo
  labels:
    app: service-demo
spec:
  selector:
    matchLabels:
      app: service-demo
  template:
    metadata:
      labels:
        app: service-demo
    spec:
      containers:
        - name: service-demo
          image: config-files/main
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,address=5015,suspend=n,quiet=y
