apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: config-playground

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: demo-configmap
    files:
      - application.yaml=configmap-sources/another.yml
  - name: second-configmap
    files:
      - application.yaml=configmap-sources/something.yml
generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true