apiVersion: v1
kind: Service
metadata:
  namespace: config-playground
  name: service-demo
  labels:
    app: service-demo
spec:
  ports:
    - port: 8080
  selector:
    app: service-demo
  type: LoadBalancer