apiVersion: v1
kind: Service
metadata:
  name: service-demo
  labels:
    app: service-demo
spec:
  ports:
    - name: app
      port: 8080
    - name: debug
      port: 5015
  selector:
    app: service-demo
